swagger: "2.0"
info:
  title: Bank Argent API Transactions documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: User Transactions API
      description: API for fetching user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: "string"
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Transaction
        "500":
          description: Internal Server Error
  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API for fetching one user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: "string"
        - in: path
          name: id
          description: id Transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Transaction
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transactions infos
      description: API for updating user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: "string"
        - in: body
          name: body
          description: Update user transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionsUpdate"
        - in: path
          name: id
          description: Update user transaction
          type: integer
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User transaction updated successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Transaction
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions module
      summary: Delete transactions infos
      description: API for deleting a transaction information
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: "string"
        - in: path
          name: id
          description: id Transaction
          type: integer
          required: true
        - in: body
          name: body
          description: delete user transaction information
          required: true
          schema:
            $ref: "#/definitions/TransactionsDelete"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction deleted successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Transaction
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    type: "object"
    properties:
      id:
        type: "integer"
      transaction type:
        type: "string"
      date:
        type: "string"
      category:
        type: "string"
      notes:
        type: "string"
      description:
        type: "string"
      amount:
        type: "number"
      title:
        type: "string"
  TransactionsUpdate:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
  TransactionsDelete:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
